### ISSUE TITLE
unable to mutate pods

### ISSUE THREAD

**Issue by raffaelespazzoli** [gatekeeper/gatekeeper-operator#142]
hello, I am unable to muatate pods, while it seems the same rule can mutate other objects.. I am tryung to udnerstand why. Here is my mutating rule:
```yaml
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: istio-injection
spec:
  match:
    scope: Namespaced
    kinds:
      - apiGroups: 
        - ''
        kinds: 
        - Pod
      # - apiGroups: ["apps"]
      #   kinds: ["ReplicaSet","StatefulSet","Deployment"]
      # - apiGroups: ["batch"]
      #   kinds: ["Job","CronJob"]                                       
  location: "metadata.annotations.'sidecar.istio.io/inject'"
  parameters:
    assign:
      value: "true"
```
If you look at the comments, those types were successfully mutated. 
And here is my webhook config
```yaml
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  validatingWebhook: Disabled
  mutatingWebhook: Enabled
  webhook:
    logLevel: INFO
    replicas: 1
    emitAdmissionEvents: Enabled
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
      - key: maistra.io/member-of
        operator: Exists
      - key: istio-injection
        operator: In
        values:
        - enabled 
  image:
    image: >-
      registry.redhat.io/rhacm2/gatekeeper-rhel8@sha256:63bd1bbb6f825fc45f2c7dc71f5f2bf118621a6b5dad8de4ad4e50eb5c720118
  audit:
    logLevel: INFO
    replicas: 1
```
One weird this is that I put the logs to debug and I can't find anything in the logs regarding pods. Are pods ignored?
Please find in attachment [gatekeeper.zip](https://github.com/gatekeeper/gatekeeper-operator/files/6097326/gatekeeper.zip) one of such log sessions.

can you help me understand what is going wrong?
