### ISSUE TITLE
[Question] Is there any way to specify operators (greater / less than) within a mutation policy?

### ISSUE THREAD

**Issue by leo8a** [gatekeeper/gatekeeper-operator#213]
Context, let's take below mutation policy as an example for a moment.
```
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: policy-gatekeeper-container-tgps
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "spec.terminationGracePeriodSeconds"
  parameters:
    assign:
      value: 40
```

Then the question is, can we define ^^ but specifying that the policy only gets applied to requests with a termination GracePeriodSeconds (tGPS) larger than 40s. Otherwise, just keep the Kubernetes default (which I think is 30s).

Sample proposal below:
```
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: policy-gatekeeper-container-tgps
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "spec.terminationGracePeriodSeconds"
  parameters:
    assign:
      value: "<40"  # this is the proposal/question
```

I was looking for an example/explanation on the [Mutation docs of Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/mutation/) but couldn't find much.
