### ISSUE TITLE
installModes options

### ISSUE THREAD

**Issue by ycao56** [gatekeeper/gatekeeper-operator#63]
```
 installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
```

Currently the gatekeeper operator uses` AllNamespaces` install mode but it is not working as expected due to gatekeeper-operator needs to set ownerReferences on gatekeeper objects. If gatekeeper CR is created in a namespace different than gatekeeper-operator's namespace, you will see following errors:

> 2020-11-17T21:56:37.061Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "operator.gatekeeper.sh", "reconcilerKind": "Gatekeeper", "controller": "gatekeeper", "name": "gatekeeper", "namespace": "openshift-openstack-infra", "error": "Unable to deploy Gatekeeper resources: Unable to set controller reference for gatekeeper-system/gatekeeper-webhook-server-cert: cross-namespace owner references are disallowed, owner's namespace openshift-openstack-infra, obj's namespace gatekeeper-system", "errorVerbose": "cross-namespace owner references are disallowed, owner's namespace openshift-openstack-infra, obj's namespace gatekeeper-system\nUnable to set controller reference for gatekeeper-system/gatekeeper-webhook-server-cert\ngithub.com/font/gatekeeper-operator/controllers.

So in my opinion, the `OwnNamespace` install mode is more appropriate.
